In [1]:
####### You are hired as data scientist to make a model to tell which on company investor should be investing ######

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import os
os.getcwd()


'C:\\Users\\pawan\\Pictures\\jupyter files'

In [5]:
dataset = pd.read_csv("50_Startups.csv");
dataset

X=dataset.iloc[:, :-1].values         #taking all rows and all columns except last column, independent variables
Y=dataset.iloc[:, 4].values           #taking last column, dependent variable

In [6]:
dataset

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [7]:
X

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79, 29491

In [8]:
Y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

In [11]:
#encoding txt into numbers for independent variables
from sklearn.preprocessing import LabelEncoder
label_encoder_X = LabelEncoder()
X[:, 3] = label_encoder_X.fit_transform(X[:,3])

In [12]:
## Library to use dummy variables
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder(categorical_features=[3])
X = onehotencoder.fit_transform(X).toarray()

C:\Users\pawan\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\pawan\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [13]:
X

array([[0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 4.8000000e+01,
        1.3689780e+05, 4.7178410e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 4.7000000e+01,
        1.5137759e+05, 4.4389853e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 4.6000000e+01,
        1.0114555e+05, 4.0793454e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 4.5000000e+01,
        1.1867185e+05, 3.8319962e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 4.4000000e+01,
        9.1391770e+04, 3.6616842e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 4.2000000e+01,
        9.9814710e+04, 3.6286136e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 4.3000000e+01,
        1.4719887e+05, 1.2771682e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 4.1000000e+01,
        1.4553006e+05, 3.2387668e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 3.9000000e+01,
        1.4871895e+05, 3.1161329e+05],
       [1.0000000e+00, 0.0000000e+00,

In [14]:
### Splitting the dataset in Training set and Test set
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

In [15]:
X_train

array([[0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.5000000e+01,
        1.0305749e+05, 2.1463481e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.3000000e+01,
        8.5047440e+04, 2.0551764e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 2.5000000e+01,
        1.4413598e+05, 1.3405007e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.4000000e+01,
        1.5769392e+05, 2.1079767e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 3.1000000e+01,
        1.1417579e+05, 2.9491957e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 4.1000000e+01,
        1.4553006e+05, 3.2387668e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 3.8000000e+01,
        1.5654742e+05, 2.5651292e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 2.0000000e+00,
        1.2415304e+05, 1.9039300e+03],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.0000000e+00,
        5.1743150e+04, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00,

In [23]:
########## Avoiding dummy variable trap ################# 
X= X[:,1:]

In [24]:
from sklearn.linear_model import LinearRegression
Regressor = LinearRegression()
Regressor.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [25]:
y_pred = Regressor.predict(X_test)

In [26]:
y_pred

array([100815.65143644, 141065.32323456, 140351.48425691,  69602.81317406,
       171849.80561971, 115796.48839868,  64138.93341566,  88177.53284684,
       114766.47156371, 165080.49074041])

In [27]:
Y_test

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

In [28]:
## Making optimal model using backward elimination

In [30]:
import statsmodels.formula.api as sn

In [31]:
#### MLR(MultiLinear Regression)####
#### MLR, y= b0 + b1*x1 + b2*x2 +.....+ bn*xn,  here b0 is constant which is not present in our data. ####
#### we can add b0 to dataset only if it is b0*x0 when x0=1 , therefore we need to add a column of 1 to dataset ####
#### here axis(parameter) determines if you want to add a line or column ####
#### axis=0(means adding line) and if axis=1(adding column) ####

In [34]:
X = np.append(arr=np.ones((50,1)).astype(int), values=X, axis=1)

In [36]:
X        # column with 1s are added

array([[1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 4.8000000e+01,
        1.3689780e+05, 4.7178410e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 4.7000000e+01,
        1.5137759e+05, 4.4389853e+05],
       [1.0000000e+00, 1.0000000e+00, 0.0000000e+00, 4.6000000e+01,
        1.0114555e+05, 4.0793454e+05],
       [1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 4.5000000e+01,
        1.1867185e+05, 3.8319962e+05],
       [1.0000000e+00, 1.0000000e+00, 0.0000000e+00, 4.4000000e+01,
        9.1391770e+04, 3.6616842e+05],
       [1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 4.2000000e+01,
        9.9814710e+04, 3.6286136e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 4.3000000e+01,
        1.4719887e+05, 1.2771682e+05],
       [1.0000000e+00, 1.0000000e+00, 0.0000000e+00, 4.1000000e+01,
        1.4553006e+05, 3.2387668e+05],
       [1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 3.9000000e+01,
        1.4871895e+05, 3.1161329e+05],
       [1.0000000e+00, 0.0000000e+00,

In [37]:
#### Backward elimination process ####

In [46]:
## making optimal model including all columns/independent vriable
## ordinary least square- method to make a model
X_opt = X[:,[0,1,2,3,4,5]]
regressor_OLS= sn.OLS(endog=Y,exog=X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.935
Model:                            OLS   Adj. R-squared:                  0.927
Method:                 Least Squares   F-statistic:                     125.8
Date:                Mon, 16 Dec 2019   Prob (F-statistic):           6.61e-25
Time:                        14:46:43   Log-Likelihood:                -532.46
No. Observations:                  50   AIC:                             1077.
Df Residuals:                      44   BIC:                             1088.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.033e+04   7948.436      6.333      0.000    3.43e+04    6.64e+04
x1          -595.2931   3882.034     -0.153      0.879   -8419.019    7228.432
x2          -678.8326   3754.684     -0.181      0.857   -8245.901    6888.236
x3          2474.4082    168.178     14.713      0.000    2135.468    2813.348
x4            -0.0289      0.060     -0.479      0.634      -0.151       0.093
x5             0.0351      0.020      1.792      0.080      -0.004       0.075
==============================================================================
Omnibus:                        6.879   Durbin-Watson:                   0.954
Prob(Omnibus):                  0.032   Jarque-Bera (JB):                5.794
Skew:                          -0.740   Prob(JB):                       0.0552
Kurtosis:                       3.770   Cond. No.                     1.39e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.39e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [49]:
### removing the independent variable with highest p value, ryt now, x1 ###
                                            ### MODEL 1 ####

In [50]:
X_opt = X[:,[0,2,3,4,5]]
regressor_OLS= sn.OLS(endog=Y,exog=X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.935
Model:                            OLS   Adj. R-squared:                  0.929
Method:                 Least Squares   F-statistic:                     160.8
Date:                Mon, 16 Dec 2019   Prob (F-statistic):           4.92e-26
Time:                        14:50:49   Log-Likelihood:                -532.47
No. Observations:                  50   AIC:                             1075.
Df Residuals:                      45   BIC:                             1085.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.017e+04   7788.618      6.441      0.000    3.45e+04    6.59e+04
x1          -394.9254   3230.846     -0.122      0.903   -6902.182    6112.332
x2          2474.9086    166.312     14.881      0.000    2139.940    2809.878
x3            -0.0292      0.060     -0.489      0.627      -0.150       0.091
x4             0.0346      0.019      1.810      0.077      -0.004       0.073
==============================================================================
Omnibus:                        6.674   Durbin-Watson:                   0.952
Prob(Omnibus):                  0.036   Jarque-Bera (JB):                5.577
Skew:                          -0.736   Prob(JB):                       0.0615
Kurtosis:                       3.713   Cond. No.                     1.37e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.37e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [51]:
                                    ### MODEL 3 ###
X_opt = X[:,[0,3,4,5]]
regressor_OLS= sn.OLS(endog=Y,exog=X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.935
Model:                            OLS   Adj. R-squared:                  0.930
Method:                 Least Squares   F-statistic:                     219.1
Date:                Mon, 16 Dec 2019   Prob (F-statistic):           3.06e-27
Time:                        14:51:22   Log-Likelihood:                -532.48
No. Observations:                  50   AIC:                             1073.
Df Residuals:                      46   BIC:                             1081.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const           5e+04   7584.184      6.593      0.000    3.47e+04    6.53e+04
x1          2472.7580    163.598     15.115      0.000    2143.452    2802.064
x2            -0.0289      0.059     -0.490      0.627      -0.148       0.090
x3             0.0349      0.019      1.852      0.071      -0.003       0.073
==============================================================================
Omnibus:                        6.748   Durbin-Watson:                   0.952
Prob(Omnibus):                  0.034   Jarque-Bera (JB):                5.661
Skew:                          -0.748   Prob(JB):                       0.0590
Kurtosis:                       3.690   Cond. No.                     1.34e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.34e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [55]:
                                    ### MODEL 4 ###
X_opt = X[:,[0,3,5]]
regressor_OLS= sn.OLS(endog=Y,exog=X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.934
Model:                            OLS   Adj. R-squared:                  0.931
Method:                 Least Squares   F-statistic:                     333.9
Date:                Mon, 16 Dec 2019   Prob (F-statistic):           1.66e-28
Time:                        14:52:23   Log-Likelihood:                -532.61
No. Observations:                  50   AIC:                             1071.
Df Residuals:                      47   BIC:                             1077.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.662e+04   3108.554     14.997      0.000    4.04e+04    5.29e+04
x1          2441.1308    149.083     16.374      0.000    2141.214    2741.047
x2             0.0378      0.018      2.132      0.038       0.002       0.073
==============================================================================
Omnibus:                        7.047   Durbin-Watson:                   0.943
Prob(Omnibus):                  0.029   Jarque-Bera (JB):                5.980
Skew:                          -0.763   Prob(JB):                       0.0503
Kurtosis:                       3.734   Cond. No.                     5.07e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.07e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""